---
- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: install-docker

    - name: Create Docker network
      ansible.builtin.include_role:
        name: create-network

    - name: Launch database
      ansible.builtin.include_role:
        name: launch-database

    - name: Launch app
      ansible.builtin.include_role:
        name: launch-app

    - name: Launch proxy
      ansible.builtin.include_role:
        name: launch-proxy
