# GitHub Actions workflow for CI - DevOps 2025
# This job builds and tests the backend application using Maven and JDK 21

name: CI devops 2025

on:
  # To begin, you want to launch this job on push and pull requests to main and develop branches
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout your GitHub code using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK) 21 using actions/setup-java@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'  # Temurin is the recommended OpenJDK distribution

      # Step 3: Build and test your application using Maven
      - name: Build and test with Maven
        run: cd simple-api && mvn clean verify
